### ISSUE TITLE
SPIKE: Evaluate the cost of retrieving all keys for an archaeologist and calculating their indices

### ISSUE THREAD

**Issue by katien** [sarcophagus-org/sarcophagus-v2-archaeologist-service#75]
- Will queries and calculations scale for an archaeologist protecting many sarcophagi?
- What is the cost of determining that a key was not derived from the archaeologist's seed?
    - Do we need to scan all possible keys for each key returned by the contracts? How can this operation be optimized?
- Evaluate using a database or writing to a file if performance becomes a concern

**Comment by sethhrbek** [comment]
Will be included in: https://github.com/sarcophagus-org/sarcophagus-v2-archaeologist-service/issues/74
