### ISSUE TITLE
Archaeologist startup logic to ensure unique key generation

### ISSUE THREAD

**Issue by katien** [sarcophagus-org/sarcophagus-v2-archaeologist-service#76]
- when the archaeologist node starts up, it should
    - retrieve the `expirationThreshold` from the smart contracts and wait that amount of time before accepting connections
    - query the smart contracts to retrieve all previously generated keys for the archaeologist
        - get all sarcophagi for archaeologist, read `cursedArchaeologist.publicKey`
        - stub method if contract data structures have not yet been updated
    - use HD wallet utility to determine the indices of all of these keys
    - set in memory index to that highest index of any previously used key +1

**Comment by sethhrbek** [comment]
Included in: https://github.com/sarcophagus-org/sarcophagus-v2-archaeologist-service/issues/74
