### ISSUE TITLE
Update negotiation signature to involve sarcophagus key

### ISSUE THREAD

**Issue by katien** [sarcophagus-org/sarcophagus-v2-archaeologist-service#78]
- during sarcophagus negotiation, an archaeologist should sign:
    - `maximumRewrapInterval`
    - `timestamp`
    - `diggingFee`
    - `publicKey` - the new key that the archaeologist generated for this sarcophagus
- remove all arweave related code from archaeologist node

**Comment by sethhrbek** [comment]
Closed via: https://github.com/sarcophagus-org/sarcophagus-v2-archaeologist-service/issues/74
