### ISSUE TITLE
Publish sarcophagus key

### ISSUE THREAD

**Issue by katien** [sarcophagus-org/sarcophagus-v2-archaeologist-service#79]
the publish job should retrieve `sarcophagus.cursedArchaeologist.publicKey` for each sarcophagus that has reached its resurrection time, then look up the corresponding private key with the HD wallet utility

**Comment by sethhrbek** [comment]
Closed via: https://github.com/sarcophagus-org/sarcophagus-v2-archaeologist-service/issues/74
